c = []
en = ["Welcome to Hangman\nMade by Rene Ehlers",
      "1. Play Game\n2. Select Language\n3. Information\n4. Exit",
      "Enter a number and press enter: ",
      "Thanks for playing!\nCheck out my GitHub\nhttps://github.com/R4W3",
      "Let's play a game of Hangman",
      "letters.",
      "Guess a letter or the word: ",
      "You already guessed the letter: ",
      " is not part of the word.",
      "Well done! ",
      " is part of the word.",
      "You have already guessed this word... : ",
      " is not the word we're looking for.",
      "Invalid input",
      "CONGRATULATIONS, You have succesfully guessed the word. It was ",
      " tries left.",
      "1. Go Back to the menu\n2. Exit",
      "You LOST, the word was: ",
      "INFORMATION:\nGuessable Words:"
      ]
de = ["Willkommen bei Galgenmännchen\nvon Rene Ehlers",
      "1. Spielen\n2. Sprache wählen\n3. Informationen\n4. Beenden",
      "Gib eine Ziffer ein und drücke Enter: ",
      "Danke fürs Spielen!\nSchau dir mein GitHub an\nhttps://github.com/R4W3",
      "Lass uns eine Runde Galgenmännchen spielen",
      "Buchstaben.",
      "Rate einen Buchstaben oder das Wort: ",
      "Den hattest du schonmal: ",
      " ist nicht Teil des Wortes.",
      "Gute gemacht! ",
      " ist Teil des Wortes.",
      "Du hast dieses Wort schon geraten... : ",
      " ist nicht das gesuchte Wort.",
      "Ungültige Eingabe",
      "GLÜCKWUNSCH! Es war ",
      " Versuche übrig.",
      "1. Zurück zum Hauptmenü\n2. Beenden",
      "Du hast VERLOREN, das Wort war: ",
      "INFORMATIONEN:\nZu erratende Worte:"
      ]
